spring.application.name=backend

# JPA
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update

# Datasource
spring.datasource.url=jdbc:mysql://localhost:3306/knowyourfan?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=password

spring.security.user.name=admin
spring.security.user.password=admin
spring.security.exclude=/**

spring.mvc.dispatch-options-request=true

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

jwt.secret=MeuSegredoSuperSecretoDePeloMenos32Bytes!!
jwt.expiration=3600000

